name: Telegram Notify on Push

on:
  push:
    branches:
      - main
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        run: |
          MESSAGE="New push by ${{ github.actor }} to ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Commit message: ${{ github.event.head_commit.message }}
          Commit URL: ${{ github.event.head_commit.url }}"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="$MESSAGE"
